spring:
  profiles:
    active: local
  application:
    name: aegis-server
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
              - openid
  session:
    redis:
      namespace: aegis:session
    timeout: ${SESSION_TIMEOUT}

exception:
  log-only-aegis-stack-trace: true

server:
  forward-headers-strategy: framework

payment:
  bank-type: ibk

time:
  zone: Asia/Seoul

discord:
  token: ${DISCORD_BOT_TOKEN}
  guild-id: ${DISCORD_GUILD_ID}
  alarm-channel-id: ${DISCORD_ALARM_CHANNEL_ID}
  complete-role-id: ${DISCORD_COMPLETE_ROLE_ID}
